
  create table "public"."abc" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "avc" jsonb not null
      );


alter table "public"."abc" enable row level security;

CREATE UNIQUE INDEX abc_pkey ON public.abc USING btree (id);

alter table "public"."abc" add constraint "abc_pkey" PRIMARY KEY using index "abc_pkey";

grant delete on table "public"."abc" to "anon";

grant insert on table "public"."abc" to "anon";

grant references on table "public"."abc" to "anon";

grant select on table "public"."abc" to "anon";

grant trigger on table "public"."abc" to "anon";

grant truncate on table "public"."abc" to "anon";

grant update on table "public"."abc" to "anon";

grant delete on table "public"."abc" to "authenticated";

grant insert on table "public"."abc" to "authenticated";

grant references on table "public"."abc" to "authenticated";

grant select on table "public"."abc" to "authenticated";

grant trigger on table "public"."abc" to "authenticated";

grant truncate on table "public"."abc" to "authenticated";

grant update on table "public"."abc" to "authenticated";

grant delete on table "public"."abc" to "postgres";

grant insert on table "public"."abc" to "postgres";

grant references on table "public"."abc" to "postgres";

grant select on table "public"."abc" to "postgres";

grant trigger on table "public"."abc" to "postgres";

grant truncate on table "public"."abc" to "postgres";

grant update on table "public"."abc" to "postgres";

grant delete on table "public"."abc" to "service_role";

grant insert on table "public"."abc" to "service_role";

grant references on table "public"."abc" to "service_role";

grant select on table "public"."abc" to "service_role";

grant trigger on table "public"."abc" to "service_role";

grant truncate on table "public"."abc" to "service_role";

grant update on table "public"."abc" to "service_role";

grant delete on table "public"."users" to "postgres";

grant insert on table "public"."users" to "postgres";

grant references on table "public"."users" to "postgres";

grant select on table "public"."users" to "postgres";

grant trigger on table "public"."users" to "postgres";

grant truncate on table "public"."users" to "postgres";

grant update on table "public"."users" to "postgres";


